/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: dc719612378e7e8932b5ca1ef79702e0)
interface __BaseEnv_CloudflareEnv {
  SOUNDCLOUD_TITLE_CACHE: KVNamespace;
  ASSETS: Fetcher;
  GITHUB_TOKEN: string;
  SC_WEB_ACCESS_TOKEN: string;
  OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./.open-next/worker');
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'GITHUB_TOKEN' | 'SC_WEB_ACCESS_TOKEN' | 'OPENAI_API_KEY'>
  > {}
}
